apiVersion: v1
kind: Service
metadata:                    # filtering, debugging, linking purpose (dashboard)
  name: catalog-service
  labels:
    app.kubernetes.io/name: catalog
spec:
  type: ClusterIP             # nodeport, loadbalancer, external name, headless service
  selector:
    app.kubernetes.io/name: catalog   # should match with deployment selector match labels
  ports:
    - name: http
      port: 8080               # service port
      targetPort: 8080         # container port
      protocol: TCP
