apiVersion: v1
kind: Pod    # deployment/service/configmap/statefulsets
metadata:
  name: catalog-pod
  labels:
    app: catalog
spec:
  containers:
    - name: catalog
      image: "public.ecr.aws/aws-containers/retail-store-sample-catalog:1.3.0"
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP
      resources:
        limits:            # maximum resource that container can consume
          cpu: "200m"
          memory: "256Mi"
        requests:          # minimum gauranteed resources
          cpu: "100m"
          memory: "128Mi"
      readinessProbe:      # healthcheck that tells k8s whether app inside the container is ready to serve traffic 
        httpGet:
          path: /health
          port: 8080